### ISSUE TITLE
Unable to find S3 credentials when connecting S3 compatible storage

### ISSUE THREAD

**Issue by sparkdemotivator** [Wh1isper/sparglim#7]
* sparglim version: The latest version
* Python version: Using Jupiter notebook provided in jupyter-sparglim-sc
* Operating System: Ubuntu 22.04, minikube version: v1.31.2

### Description

Unable to find S3 credentials when connecting S3 compilable storage (i.e. minio)

### What I Did

I successfully executed spark plan with Spark Connect and Jupyter Notebook installed by following the guide in https://github.com/Wh1isper/sparglim/tree/main/examples/jupyter-sparglim-sc/k8s.

For next, I'd like to test its ability to connect S3-compatible storage, such as Minio. But it failed and returned an error **"org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider"**

I have successfully tested the connection to my S3-compatible storage using local pyspark with the same configurations. Additionally, I have conducted network testing inside Minikube and found no network blockage to my S3 storage. 

It seems that it didn't use the access key and secret key provided in spark conf. But not sure the root cause.

Full error log

![image](https://github.com/Wh1isper/sparglim/assets/147146130/3765bcfe-941f-4b08-bbc8-b57ad798c48d)

The code for connecting S3
```
from pyspark.sql import SparkSession
from pyspark import SparkConf

# Set Spark Connection Config

conf = SparkConf()
# ----------------------------- Spark Connect ----------------------------- #
conf.set("spark.remote", "sc://192.168.49.1:30052")
conf.set("spark.app.name", "<Spark App Name>")
# ----------------------------- S3 --------------------------------------- #
conf.set("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
conf.set("spark.hadoop.fs.s3a.path.style.access", "true")
conf.set("spark.hadoop.fs.s3a.connection.ssl.enabled", "true")
conf.set("spark.hadoop.fs.s3a.endpoint", "https://<My S3 Endpoint>.com:10443")
conf.set("spark.hadoop.fs.s3a.access.key", "<My S3 Access Key>")
conf.set("spark.hadoop.fs.s3a.secret.key", "<My S3 Secret Key>")

spark = SparkSession.builder.config(conf=conf).getOrCreate()

df = spark.read.text("s3a://<S3 Path of my file>/test.txt")
df.show()
```

**Comment by Wh1isper** [comment]
In Spark Connect, the `SparkSession` using `spark.remote` is a **client**, and the data fetching and computation happens on the **Server** side, which is the `sparglim-server` you deployed on K8S and its `executor`

So you need to configure `s3a` information on the service side.

Sparglim currently takes configurations via the environment variable: https://github.com/Wh1isper/sparglim/blob/main/config.md

In your case, add `S3_ACCESS_KEY`, `S3_SECRET_KEY` and `S3_ENTRY_POINT` should just work.

Example of `deployment.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparglim-server
  namespace: sparglim
  labels:
    app: sparglim-server
spec:
  replicas: 1

  selector:
    matchLabels:
      app: sparglim-server
  template:
    metadata:
      labels:
        app: sparglim-server
    spec:
      containers:
        - name: sparglim-server
          image: wh1isper/sparglim-server
          ports:
            - containerPort: 15002
          imagePullPolicy: Always
          env:
            - name: SPARGLIM_SERVER_MODE
              value: "k8s"
            - name: SPARGLIM_DRIVER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARGLIM_DRIVER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # S3 auth and entrypoint
            - name: S3_ACCESS_KEY
              value: <Your access key>
            - name: S3_SECRET_KEY
              value: <Your secret key>
            - name: S3_ENTRY_POINT
              value: <Your entrypoint>
```

**In a production environment, consider using SECRET**: https://kubernetes.io/docs/concepts/configuration/secret/

The client side does not need any S3 information:

```python
from pyspark.sql import SparkSession
from pyspark import SparkConf

# Set Spark Connection Config

conf = SparkConf()
conf.set("spark.remote", "sc://192.168.49.1:30052")
conf.set("spark.app.name", "<Spark App Name>")

spark = SparkSession.builder.config(conf=conf).getOrCreate()

df = spark.read.text("s3a://<S3 Path of my file>/test.txt")
df.show()
```

You can also try `sparglim` 's connect client mode:

```python
import os
os.environ["SPARGLIM_REMOTE"] = "sc://<master-ip>:30052" # Also avaliable `export SPARGLIM_REMOTE=sc://<master-ip>:30052` before start python

from sparglim.config.builder import ConfigBuilder

c = ConfigBuilder().config_connect_client()
spark = c.get_or_create()
```
